channels:
  telegram:
    bot:
      enabled: true
      name: "ConferenceRequesterBot"
      token: "868656591:AAEN_gOc2GQa4zo5Gp4KWPq1Rt_XgZBuSgY"
      proxy:
        enabled: true
        host: "127.0.0.1"
        port: 9150
        type: SOCKS5

spring:
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    url: "jdbc:h2:mem:~/test"
  h2:
    console:
      enabled: true
